# Generated by Django 4.2.7 on 2025-10-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
