# Generated by Django 5.2.7 on 2025-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_registration_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='auth_provider',
            field=models.CharField(default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
